import type { FontEntry, FontCategory } from '../types/canvas';

export const FONT_CATEGORIES: { id: FontCategory; label: string; labelEn: string }[] = [
  { id: 'sans-serif', label: '无衬线', labelEn: 'Sans-serif' },
  { id: 'serif', label: '衬线', labelEn: 'Serif' },
  { id: 'display', label: '展示', labelEn: 'Display' },
  { id: 'monospace', label: '等宽', labelEn: 'Monospace' },
  { id: 'chinese', label: '中文', labelEn: 'Chinese' },
];

export const BUILTIN_FONTS: FontEntry[] = [
  // Sans-serif
  { name: 'Inter', value: '"Inter", system-ui, sans-serif', category: 'sans-serif' },
  { name: 'Roboto', value: '"Roboto", sans-serif', category: 'sans-serif' },
  { name: 'Open Sans', value: '"Open Sans", sans-serif', category: 'sans-serif' },
  { name: 'Lato', value: '"Lato", sans-serif', category: 'sans-serif' },
  { name: 'Montserrat', value: '"Montserrat", sans-serif', category: 'sans-serif' },
  { name: 'Oswald', value: '"Oswald", sans-serif', category: 'sans-serif' },
  { name: 'Raleway', value: '"Raleway", sans-serif', category: 'sans-serif' },
  { name: 'Poppins', value: '"Poppins", sans-serif', category: 'sans-serif' },
  { name: 'Nunito', value: '"Nunito", sans-serif', category: 'sans-serif' },
  { name: 'Source Sans', value: '"Source Sans Pro", sans-serif', category: 'sans-serif' },
  { name: 'PT Sans', value: '"PT Sans", sans-serif', category: 'sans-serif' },
  { name: 'Ubuntu', value: '"Ubuntu", sans-serif', category: 'sans-serif' },
  { name: 'Fira Sans', value: '"Fira Sans", sans-serif', category: 'sans-serif' },
  { name: 'Work Sans', value: '"Work Sans", sans-serif', category: 'sans-serif' },
  { name: 'Mulish', value: '"Mulish", sans-serif', category: 'sans-serif' },
  { name: 'Noto Sans', value: '"Noto Sans", sans-serif', category: 'sans-serif' },
  // Serif
  { name: 'Playfair Display', value: '"Playfair Display", serif', category: 'serif' },
  { name: 'Merriweather', value: '"Merriweather", serif', category: 'serif' },
  { name: 'Lora', value: '"Lora", serif', category: 'serif' },
  { name: 'Crimson Text', value: '"Crimson Text", serif', category: 'serif' },
  { name: 'Libre Baskerville', value: '"Libre Baskerville", serif', category: 'serif' },
  { name: 'Georgia', value: 'Georgia, serif', category: 'serif' },
  { name: 'Times New Roman', value: '"Times New Roman", serif', category: 'serif' },
  { name: 'PT Serif', value: '"PT Serif", serif', category: 'serif' },
  { name: 'Source Serif', value: '"Source Serif Pro", serif', category: 'serif' },
  // Display/Decorative
  { name: 'Bebas Neue', value: '"Bebas Neue", cursive', category: 'display' },
  { name: 'Abril Fatface', value: '"Abril Fatface", cursive', category: 'display' },
  { name: 'Lobster', value: '"Lobster", cursive', category: 'display' },
  { name: 'Pacifico', value: '"Pacifico", cursive', category: 'display' },
  { name: 'Dancing Script', value: '"Dancing Script", cursive', category: 'display' },
  { name: 'Satisfy', value: '"Satisfy", cursive', category: 'display' },
  { name: 'Righteous', value: '"Righteous", cursive', category: 'display' },
  { name: 'Alfa Slab', value: '"Alfa Slab One", cursive', category: 'display' },
  { name: 'Anton', value: '"Anton", sans-serif', category: 'display' },
  { name: 'Bungee', value: '"Bungee", cursive', category: 'display' },
  // Monospace
  { name: 'JetBrains Mono', value: '"JetBrains Mono", monospace', category: 'monospace' },
  { name: 'Fira Code', value: '"Fira Code", monospace', category: 'monospace' },
  { name: 'Source Code', value: '"Source Code Pro", monospace', category: 'monospace' },
  { name: 'Inconsolata', value: '"Inconsolata", monospace', category: 'monospace' },
  { name: 'Roboto Mono', value: '"Roboto Mono", monospace', category: 'monospace' },
  { name: 'Courier New', value: '"Courier New", monospace', category: 'monospace' },
  // Chinese fonts
  { name: '微软雅黑', value: '"Microsoft YaHei", sans-serif', category: 'chinese' },
  { name: '微软雅黑 Bold', value: '"Microsoft YaHei", "Microsoft YaHei Bold", sans-serif', category: 'chinese' },
  { name: '黑体', value: 'SimHei, "STHeiti", sans-serif', category: 'chinese' },
  { name: '宋体', value: 'SimSun, "STSong", serif', category: 'chinese' },
  { name: '楷体', value: 'KaiTi, "STKaiti", serif', category: 'chinese' },
  { name: '仿宋', value: 'FangSong, "STFangsong", serif', category: 'chinese' },
  { name: '幼圆', value: 'YouYuan, sans-serif', category: 'chinese' },
  { name: '华文黑体', value: '"STHeiti", sans-serif', category: 'chinese' },
  { name: '华文宋体', value: '"STSong", serif', category: 'chinese' },
  { name: '华文楷体', value: '"STKaiti", serif', category: 'chinese' },
  { name: '华文仿宋', value: '"STFangsong", serif', category: 'chinese' },
  { name: '思源黑体', value: '"Source Han Sans SC", "Noto Sans SC", sans-serif', category: 'chinese' },
  { name: '思源宋体', value: '"Source Han Serif SC", "Noto Serif SC", serif', category: 'chinese' },
  { name: '苹方', value: '"PingFang SC", sans-serif', category: 'chinese' },
  { name: '苹方-简', value: '"PingFang SC Regular", sans-serif', category: 'chinese' },
  { name: '苹方-中', value: '"PingFang SC Medium", sans-serif', category: 'chinese' },
  { name: '苹方-粗', value: '"PingFang SC Semibold", sans-serif', category: 'chinese' },
];
